### ISSUE TITLE
Strings Gens with specific length and ranges

### ISSUE THREAD

**Issue by chesedo** [leanovate/gopter#11]
In the docs I can see that [GenParameters.WithSize()](https://godoc.org/github.com/leanovate/gopter#GenParameters.WithSize) can be used to control the maximum length of string arbitraries, but I can not figure out how to use it to limit the length of strings generated by `gen.AlphaString()`, `gen.AnyString`, `gen.NumString()`, etc.

In the code they all call `genString()`, which in turn calls `SliceOf()`, which then makes use of `genParams.Size` (from GenParameters), but `genParams` gets passed in by some internal function and I do not know how to control this.

On the flip side I see that `SliceOfN()` will allow an int parameter to specify the length, but my attempts to create a generator using it fails, as using the same map as `genString()` wants a `rune` and not `[]rune`.

**Comment by untoldwind** [comment]
Sorry for the delay I was somewhat busy with a lot of other stuff.

You are right, the API is probably a bit lacking in this regard.
On the other hand there a various options to derive a generator that fits your needs.

If you just require a string with a certain minimum size (i.e. non-empty strings), the easiest solution would be to just add a sieve:

gen.AnyString().SuchThat(func (v string) bool { return len(v) > 1 })

If you need a strings of a specific length, then yes you should use SliceOfN:

gen.SliceOfN(100, gen.Rune()).Map(func (v []rune) string { return string(v) })

**Comment by johanbrandhorst** [comment]
Using `TestParameters` as a parameter to `prop.Check` to control the size of generated slices seems fairly broken, at the moment `MinSize` is translated into the `GenParameters.Size` (https://github.com/leanovate/gopter/blob/0a692bbdefaf520798e0ecedfac3b86432f4d96e/prop.go#L34), which means slices are generated with the `MinSize` as an (exclusive) upper bound (because of the use of `rand.Intn` in https://github.com/leanovate/gopter/blob/0a692bbdefaf520798e0ecedfac3b86432f4d96e/gen/slice_of.go#L14, which generates a number exclusive of the upper bound).

**Comment by johanbrandhorst** [comment]
I've added a PR that deals with this such that my use case is fixed. I left the `MaxSize` being exclusive since that might've been intentional.

**Comment by untoldwind** [comment]
Just left a note on the PR. If you fix that I'm happy to merge.
